viewy/accounts/urls.py
from django.urls import path
from .views import (
  RegistUserView, InvitedRegistUserView, RegistAdvertiserView, UserLoginView, UserLogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetSendView, PasswordResetCompleteView, FollowView, EditPrfView,CheckAgeView, VerifyView, ResendVerificationCodeView, MessageListView, MessageDetailView, MessageDeleteView, SearchHistoryView, SearchHistorySaveView, HideSearchHistoriesView, DeleteUserView, ChangeDimensionView, FirstSettingView, SurveyAnswerView, SaveNotificationView, SaveFreezeNotificationView, BlockView, BlockPosterView, LoginAPIView, RegisterAPIView, SetCookieView,RegistEndView
)
from . import views

app_name = 'accounts'
urlpatterns = [ 
  path('regist/', RegistUserView.as_view(), name='regist'),  
  path('invited_regist/', InvitedRegistUserView.as_view(), name='invited_regist'),
  path('regist_advertiser/', RegistAdvertiserView.as_view(), name='regist_advertiser'),
  path('user_login/', UserLoginView.as_view(), name='user_login'),
  path('special_login/', UserLoginView.as_view(), name='special_login'),    
  path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
  path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
  path('password_reset_send/', PasswordResetSendView.as_view(), name='password_reset_send'),
  path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
  path('follow/<int:pk>/', FollowView.as_view(), name='follow'),
  path('block/<int:pk>/', BlockView.as_view(), name='block'),
  path('block_poster/<int:post_id>/', BlockPosterView.as_view(), name='block_poster'),
  path('edit_prf/', EditPrfView.as_view(), name='edit_prf'),
  path('check_age/', CheckAgeView.as_view(), name='check_age'),
  path('verify/', VerifyView.as_view(), name='verify'),
  path('resend_verification/', ResendVerificationCodeView.as_view(), name='resend_verification'),
  path('messages/', MessageListView.as_view(), name='message_list'),
  path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
  path('messages/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
  path('search_history/', views.SearchHistoryView.as_view(), name='search_history'),
  path('save_search_history/', views.SearchHistorySaveView.as_view(), name='save_search_history'),
  path('hide_search_histories/', views.HideSearchHistoriesView.as_view(), name='hide_search_histories'),
  path('delete_user/', DeleteUserView.as_view(), name='delete_user'),   
  path('change_dimension/', ChangeDimensionView.as_view(), name='change_dimension'),
  path('first_setting/', FirstSettingView.as_view(), name='first_setting'),
  path('survey_answer/<int:selected_option_id>/', SurveyAnswerView.as_view(), name='survey_answer'),
  path('save_notification_view/', SaveNotificationView.as_view(), name='save_notification_view'),
  path('save_freeze_notification_view/', SaveFreezeNotificationView.as_view(), name='save_freeze_notification_view'),
  path('login_api/', LoginAPIView.as_view(), name='login_api'),
  path('register_api/', RegisterAPIView.as_view(), name='login_api'),
  path('set_cookie/', SetCookieView.as_view(), name='set_cookie'),
  path('regist_end/', RegistEndView.as_view(), name='regist_end'),
]

viewy/advertisement/urls.py
from django.urls import path
from .views import (
  AdCampaignsListView, AdCampaignDetailView, CampaignFormView, AdMangaCreateView, AdVideoCreateView, IsHiddenToggle, AdViewButton, EditAdCampaignView, AdCampaignStatusView, AdInfoDelete, AdCampaignDelete, AdClickCountView, FilteredAdCampaignsListView, CloseAdCampaignsListView, BillingView, AdEditPrf
)
from . import views

app_name = 'advertisement'

urlpatterns = [ 
  path('ad_campaigns_list/', AdCampaignsListView.as_view(), name='ad_campaigns_list'),
  path('ad_campaigns/<str:status>/', FilteredAdCampaignsListView.as_view(), name='filtered_ad_campaign_list'),
  path('advertisement/close/', CloseAdCampaignsListView.as_view(), name='close_ad_campaigns_list'),
  path('ad_campaign_detail/<int:campaign_id>/', AdCampaignDetailView.as_view(), name='ad_campaign_detail'),
  path('campaign_form/', CampaignFormView.as_view(), name='campaign_form'),
  path('ad_manga_create/', AdMangaCreateView.as_view(), name='ad_manga_create'),
  path('ad_video_create/', AdVideoCreateView.as_view(), name='ad_video_create'),
  path('is_hidden_toggle/', IsHiddenToggle.as_view(), name='is_hidden_toggle'),
  path('ad_view_button/<int:post_id>/', AdViewButton.as_view(), name='ad_view_button'),
  path('edit_ad_campaign/<int:campaign_id>/', EditAdCampaignView.as_view(), name='edit_ad_campaign'),
  path('ad_campaign_status/<int:campaign_id>/', AdCampaignStatusView.as_view(), name='ad_campaign_status'),
  path('delete_ad_info/<int:ad_info_id>/', AdInfoDelete.as_view(), name='delete_ad_info'),
  path('delete_ad_campaign/<int:campaign_id>/', AdCampaignDelete.as_view(), name='delete_ad_campaign'),
  path('ad_edit_prf/', AdEditPrf.as_view(), name='ad_edit_prf'),
  path('ad_click_count/<int:post_id>/', AdClickCountView.as_view(), name='ad_click_count'),
  path('billings/', BillingView.as_view(), name='billings'),
]

viewy/posts/urls.py
from django.urls import path
from .views import (
 MangaCreateView, VisitorPostListView, PostListView, VideoCreateView, StarView, FavoriteView, RecommendPostView, GetRecommendUsers, FavoritePostListView, PosterPageView, HashtagPostListView, HashtagDimensionChangeView, HashtagPageView, FollowListView, FollowPageView, GetMoreFollowView, GetMorePreviousFollowView, GetMorePreviousCollectionView, DeleteCollectionView, RenameCollectionView, PosterPostListView, MyAccountView, SettingView, PinPostView, DeletePostView, AddPostView, SearchPageView, HotHashtagView, FavoritePageView, CollectionsMenuView, CollectionPageView, CollectionPostListView, GetMoreCollectionView, CreateNewCollection, BePartnerPageView, SubmitReportView, MyPostView, HiddenPostView, UnpublishedPostView, UpdateScheduledTimeView, AutoCorrectView, GetMorePostsView, GetMoreFavoriteView, GetMorePreviousFavoriteView, GetMorePosterPostsView, GetMorePreviousPosterPostsView, GetMoreHashtagView, GetMorePreviousHashtagView, AdsViewCount, WideAdsViewCount, AdsClickCount, WideAdsClickCount, AddToCollectionView, RemoveFromCollectionView, CreateCollectionAndAddPost, CollectionsForPostView, MyFollowListView, MyBlockListView, FreezeNotificationRequest, FreezeNotificationRequestSuccessView, FreezeListView, EmoteCountView, ViewDurationCountView, ShowMessageView, TestStreamingView, HandleEventParticipationView
)

app_name = 'posts'

urlpatterns = [
   path('manga_create/', MangaCreateView.as_view(), name='manga_create'),
   path('video_create/', VideoCreateView.as_view(), name='video_create'),
   path('postlist/', PostListView.as_view(), name='postlist'),
   path('visitor_postlist/', VisitorPostListView.as_view(), name='visitor_postlist'),
   path('get_more_posts/', GetMorePostsView.as_view(), name='get_more_posts'),
   path('star/', StarView.as_view(), name='star'),
   path('favorite/<int:pk>/', FavoriteView.as_view(), name='favorite'),
   path('recommend/', RecommendPostView.as_view(), name='recommend'),
   path('get_recommend_users/<int:post_id>/', GetRecommendUsers.as_view(), name='get_recommend_users'),
   path('fovorite_page/', FavoritePageView.as_view(), name='favorite_page'),
   path('fovorite_list/', FavoritePostListView.as_view(), name='favorite_list'),
   path('get_more_favorite/',  GetMoreFavoriteView.as_view(), name='get_more_favorite'),
   path('get_more_previous_favorite/',  GetMorePreviousFavoriteView.as_view(), name='get_more_previous_favorite'),
   path('collections_menu/', CollectionsMenuView.as_view(), name='collections_menu'),
   path('collection_page/<int:collection_id>/', CollectionPageView.as_view(), name='collection_page'),
   path('collection_list/<int:collection_id>/', CollectionPostListView.as_view(), name='collection_list'),
   path('get_more_collection/', GetMoreCollectionView.as_view(), name='get_more_collection'),
   path('get_more_previous_collection/', GetMorePreviousCollectionView.as_view(), name='get_more_previous_collection'),
   path('delete_collection/<int:collection_id>/', DeleteCollectionView.as_view(), name='delete_collection'),
   path('rename_collection/<int:collection_id>/', RenameCollectionView.as_view(), name='rename_collection'),
   path('create_new_collection/', CreateNewCollection.as_view(), name='create_new_collection'),
   path('hashtag_dimension_change/', HashtagDimensionChangeView.as_view(), name='hashtag_dimension_change'),
   path('hashtag/<str:hashtag>/', HashtagPageView.as_view(), name='hashtag'),
   path('hashtag_list/<str:hashtag>/', HashtagPostListView.as_view(), name='hashtag_list'),
   path('get_more_hashtag/', GetMoreHashtagView.as_view(), name='get_more_hashtag'),
   path('get_more_previous_hashtag/', GetMorePreviousHashtagView.as_view(), name='get_more_previous_hashtag'),
   path('posts/follow_list/', FollowListView.as_view(), name='follow_list'),
   path('follow_page/', FollowPageView.as_view(), name='follow_page'),
   path('get_more_follow/',  GetMoreFollowView.as_view(), name='get_more_follow'),
   path('get_more_previous_follow/',  GetMorePreviousFollowView.as_view(), name='get_more_previous_follow'),
   # path('back/', BackView.as_view(), name='back'),
   path('poster_page/<str:username>/', PosterPageView.as_view(), name='poster_page'),
   path('poster_post_list/<str:username>/', PosterPostListView.as_view(), name='poster_post_list'),
   path('get_more_poster_posts/',  GetMorePosterPostsView.as_view(), name='get_more_poster_posts'),
   path('get_more_previous_poster_posts/',  GetMorePreviousPosterPostsView.as_view(), name='get_more_previous_poster_posts'), 
   path('add_post/', AddPostView.as_view(), name='add_post'),
   path('my_account/', MyAccountView.as_view(), name='my_account'),   
   path('my_posts/', MyPostView.as_view(), name='my_posts'), 
   path('hidden_post/', HiddenPostView.as_view(), name='hidden_post'), 
   path('unpublished_post/', UnpublishedPostView.as_view(), name='unpublished_post'), 
   path('update_scheduled_time/', UpdateScheduledTimeView.as_view(), name='update_scheduled_time'),
   path('my_follow_list/', MyFollowListView.as_view(), name='my_follow_list'),
   path('block-list/', MyBlockListView.as_view(), name='block_list'),
   path('freeze_notification_request/', FreezeNotificationRequest.as_view(), name='freeze_notification_request'),
   path('freeze_notification_request_success/', FreezeNotificationRequestSuccessView.as_view(), name='freeze_notification_request_success'),
   path('freeze-list/', FreezeListView.as_view(), name='freeze_list'),
   path('pin_post/', PinPostView.as_view(), name='pin_post'),
   path('delete_post/', DeletePostView.as_view(), name='delete_post'),
   path('setting/', SettingView.as_view(), name='setting'),   
   path('searchpage/', SearchPageView.as_view(), name='searchpage'),
   path('hothashtag/', HotHashtagView.as_view(), name='hothashtag'),
   path('auto_correct/', AutoCorrectView.as_view(), name='auto_correct'),
   path('be_partner/', BePartnerPageView.as_view(), name='be_partner'),
   path('ads_view_count/<int:ad_id>', AdsViewCount.as_view(), name='ads_view_count'),
   path('wideads_view_count/<int:ad_id>', WideAdsViewCount.as_view(), name='wideads_view_count'),
   path('ads_click_count/<int:ad_id>', AdsClickCount.as_view(), name='ads_click_count'),
   path('wideads_click_count/<int:ad_id>', WideAdsClickCount.as_view(), name='Wideads_click_count'),
   path('add_to_collection/', AddToCollectionView.as_view(), name='add_to_collection'),
   path('remove_from_collection/', RemoveFromCollectionView.as_view(), name='remove_from_collection'),
   path('create_collection_and_add_post/', CreateCollectionAndAddPost.as_view(), name='create_collection_and_add_post'),
   path('get_collections_for_post/<int:post_id>/', CollectionsForPostView.as_view(), name='get_collections_for_post'),
   path('report/', SubmitReportView.as_view(), name='report'),
   path('emote_count/<int:post_id>/<int:emote_number>/', EmoteCountView.as_view(), name='emote_count'),
   path('view_duration_count/', ViewDurationCountView.as_view(), name='view_duration_count'),
   path('show_message/', ShowMessageView.as_view(), name='show_message'),
   path('test_streaming/', TestStreamingView.as_view(), name='test_streaming'),
   path('handle_event_participation/', HandleEventParticipationView.as_view(), name='handle_event_participation'),
]

viewy/templates/advertisement/achieved.html
{% extends 'advertisement/ad_campaigns_list.html' %}
{% load extra_filters %}
{% block table %}
<div class="sub-page-title">目標達成したキャンペーン</div>

<div class="filter">
  絞り込み：
  <a href="{% url 'advertisement:close_ad_campaigns_list' %}" class="status-button" style="background-color: rgba(193, 193, 193, 0.76);">目標達成</a>
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='stopped' %}" class="status-button">途中停止</a>
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='expired' %}" class="status-button">期限到達</a>
</div>

<div class="block">

  <table>
    <tr>
      <th>CPM/CPC</th>
      <th>キャンペーンタイトル</th>
      <th>広告数</th>
      <th>合計数/目標数</th>
      <th>料金 / 見積金額</th>
      <th>表示期間</th>
      <th>停止／公開</th>
    </tr>
    {% for campaign in campaigns %}
    {% if campaign.status == 'achieved' %}
    <tr class="release-campaign">
      <td>{{ campaign.pricing_model }}</td>
      <td>
        <a href="{% url 'advertisement:ad_campaign_detail' campaign.id %}" class="campaign-title">
          {{ campaign.title }}
        </a>
      </td>
      <td>{{ campaign.adinfos_count }}</td>
      <td class="views">
        {% if campaign.pricing_model == 'CPM' %}
        <span>{{ campaign.total_views_count|add_commas }}</span>
        <span>/{{ campaign.target_views|add_commas }}</span>
        {% elif campaign.pricing_model == 'CPC' %}
        <span>{{ campaign.total_clicks_count|add_commas }}</span>
        <span>/{{ campaign.target_clicks|add_commas }}</span>
        {% endif %}
      </td>
      <td>{{ campaign.fee|add_commas }} / {{ campaign.budget|add_commas }}</td>
      <td data-end-date="{{ campaign.end_date|date:" Y-m-d" }}" class="date-cell">
        <span class="date">
          {{ campaign.start_date|date:"Y-m-d" }}
        </span>～<br>
        <span class="date">
          {{ campaign.end_date|date:"Y-m-d" }}</span>
      </td>
      <td>
        {% if campaign.status == 'achieved' %}
        <form>
          <button class="release-button  disabled-button">
            目標達成
          </button>
        </form>
        {% endif %}
      </td>
    </tr>
    {% endif %}
    {% empty %}
    <tr>
      <td colspan="7">データはありません。</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

viewy/templates/advertisement/ad_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/advertisement/ad_base.css' %}">
  <script src="https://kit.fontawesome.com/ad23325601.js" crossorigin="anonymous"></script>
  <title>Viewy-advertisement</title>
  {% block head %}
  {% endblock %}
</head>
<body>

  <div class="screen">
    <div class="side-menu">
      <div class="main-title">
        <img class="prf_img" src="{{user.prf_img.url}}" alt="">
        <div>
          {% if user.displayname %}
              {{ user.displayname }}様の
          {% else %}
              {{ user.username }}様の
          {% endif %}
        </div>
        <div>広告管理ページ</div>
      </div>
      <a href="{% url 'advertisement:ad_edit_prf'%}"><i class="fa-solid fa-user menu-icon"></i></i><span class="menu-title">プロフィール編集</span></a>
      <a href="{% url 'advertisement:ad_campaigns_list'%}"><i class="fa-solid fa-receipt menu-icon"></i><span class="menu-title">キャンペーン</span></a>
      <div class="campaign-status">
        <a href="{% url 'advertisement:filtered_ad_campaign_list' status='pending' %}" class="status-button sub-status">公開前</a>
        <a href="{% url 'advertisement:filtered_ad_campaign_list' status='running' %}" class="status-button sub-status">公開中</a>
        <a href="{% url 'advertisement:close_ad_campaigns_list' %}" class="status-button sub-status">非公開</a>
      </div>
      <a href="{% url 'advertisement:campaign_form'%}"><i class="fa-solid fa-rectangle-ad menu-icon"></i><span class="menu-title">キャンペーン作成</span></a>
      <a href="{% url 'advertisement:ad_manga_create'%}"><i class="fa-solid fa-images menu-icon"></i><span class="menu-title">画像広告作成</span></a>
      <a href="{% url 'advertisement:ad_video_create'%}"><i class="fa-solid fa-film menu-icon"></i><span class="menu-title">動画広告作成</span></a>
      <a href="{% url 'advertisement:billings'%}"><i class="fa-solid fa-yen-sign menu-icon"></i><span class="menu-title">料金</span></a>
      <a href="{% url 'posts:my_account'%}" class="back"><i class="fa-solid fa-arrow-right-from-bracket menu-icon"></i><span class="menu-title">Viewyに戻る</span></a>
    </div>

    <div class="contents">
      {% block content %}
      {% endblock %}
    </div>

  </div>



  {% block script %}
  {% endblock %}
  <div class="wall">

    <div class="wall-message">
      <div class="wall-tom">
        <img src="{{ MEDIA_URL }}others/熟睡.png" alt="">
      </div>
      <div>
        こちらの管理画面は横幅が1200px以上でないとご使用いただけません。お手数ですがパソコン等からログインしなおしてください。
      </div>
    </div>
  </div>
</body>
</html>

viewy/templates/advertisement/billings.html
{% extends 'advertisement/ad_base.html' %}
{% load static %}
{% load extra_filters %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/advertisement/ad_campaign_list.css' %}">
<link rel="stylesheet" href="{% static 'css/advertisement/billings.css' %}">
{% endblock %}

{% block content %}
{% block table %}
<div class="page-title">請求履歴</div>
<div class="block">
  <form method="get" action="{% url 'advertisement:billings' %}">
    <div class="table-set">
      {{ form.as_p }}
      <button type="submit">表示</button>
    </div>
  </form>
  <table>
    <thead>
      <tr>
        <th>キャンペーン名</th>
        <th>請求料金</th>
      </tr>
    </thead>
    <tbody>
      {% for billing in campaign_billings %}
      <tr>
        <td>
          <a href="{% url 'advertisement:ad_campaign_detail' billing.campaign_id %}" class="campaign-title">
            {{ billing.campaign_title }}</a>
        </td>
        <td style="text-align: right;">{{ billing.monthly_fee|add_commas }}円</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">キャンペーンの月末請求履歴はありません。</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td style="text-align: right;">合計 {{ total_fee|add_commas }}円</td>
      </tr>
      <tr>
        <td></td>
        <td style="text-align: right;">税込 {{ total_fee_with_tax|add_commas }}円</td>
      </tr>
    </tfoot>
  </table>

</div>
{% endblock %}
{% endblock %}
{% block script %}

{% endblock %}

viewy/templates/advertisement/expired.html
{% extends 'advertisement/ad_campaigns_list.html' %}
{% load extra_filters %}
{% block table %}
<div class="sub-page-title">終了期限に到達にしたキャンペーン</div>

<div class="filter">
  絞り込み：
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='achieved' %}" class="status-button">目標達成</a>
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='stopped' %}" class="status-button">途中停止</a>
  <a href="{% url 'advertisement:close_ad_campaigns_list' %}" class="status-button" style="background-color: rgba(193, 193, 193, 0.76);">期限到達</a>
</div>
<div class="warning">※終了期限に到達した時点での、実際の表示回数/クリック数に基づいて、CPM/CPCが再計算され料金が確定します
</div>
<div class="block">

  <table>
    <tr>
      <th>CPM/CPC</th>
      <th>キャンペーンタイトル</th>
      <th>広告数</th>
      <th>合計数/目標数</th>
      <th>料金 / 見積金額</th>
      <th>表示期間</th>
      <th>停止／公開</th>
    </tr>
    {% for campaign in campaigns %}
    {% if campaign.status == 'expired' %}
    <tr class="release-campaign">
      <td>{{ campaign.pricing_model }}</td>
      <td>
        <a href="{% url 'advertisement:ad_campaign_detail' campaign.id %}" class="campaign-title">
          {{ campaign.title }}
        </a>
      </td>
      <td>{{ campaign.adinfos_count }}</td>
      <td class="views">
        {% if campaign.pricing_model == 'CPM' %}
        <span>{{ campaign.total_views_count|add_commas }}</span>
        <span>/{{ campaign.target_views|add_commas }}</span>
        {% elif campaign.pricing_model == 'CPC' %}
        <span>{{ campaign.total_clicks_count|add_commas }}</span>
        <span>/{{ campaign.target_clicks|add_commas }}</span>
        {% endif %}
      </td>
      <td>{{ campaign.fee|add_commas }} / {{ campaign.budget|add_commas }}</td>
      <td data-end-date="{{ campaign.end_date|date:" Y-m-d" }}" class="date-cell">
        <span class="date">
          {{ campaign.start_date|date:"Y-m-d" }}
        </span>
        ～<br>
        <span class="date">
          {{ campaign.end_date|date:"Y-m-d" }}</span>
      </td>
      <td>
        {% if campaign.status == 'expired' %}
        <form>
          <button class="release-button  disabled-button">
            終了期限に到達
          </button>
        </form>
        {% endif %}
      </td>
    </tr>
    {% endif %}
    {% empty %}
    <tr>
      <td colspan="7">データはありません。</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

viewy/templates/advertisement/running.html
{% extends 'advertisement/ad_campaigns_list.html' %}
{% load extra_filters %}
{% block table %}
<div class="sub-page-title">公開中のキャンペーン</div>

<div class="block">

  <table>
    <tr>
      <th>CPM/CPC</th>
      <th>キャンペーンタイトル</th>
      <th>広告数</th>
      <th>合計数/目標数</th>
      <th>料金 / 見積金額</th>
      <th>表示期間</th>
      <th>停止／公開</th>
    </tr>
    {% for campaign in campaigns %}
    {% if campaign.status == 'running' %}
    <tr class="release-campaign">
      <td>{{ campaign.pricing_model }}</td>
      <td>
        <a href="{% url 'advertisement:ad_campaign_detail' campaign.id %}" class="campaign-title">
          {{ campaign.title }}
        </a>
      </td>
      <td>{{ campaign.adinfos_count }}</td>
      <td class="views">
        {% if campaign.pricing_model == 'CPM' %}
        <span>{{ campaign.total_views_count|add_commas }}</span>
        <span>/{{ campaign.target_views|add_commas }}</span>
        {% elif campaign.pricing_model == 'CPC' %}
        <span>{{ campaign.total_clicks_count|add_commas }}</span>
        <span>/{{ campaign.target_clicks|add_commas }}</span>
        {% endif %}
      </td>
      <td>{{ campaign.fee|add_commas }} / {{ campaign.budget|add_commas }}</td>
      <td data-end-date="{{ campaign.end_date|date:" Y-m-d" }}" class="date-cell">
        <span class="date">
          {{ campaign.start_date|date:"Y-m-d" }}
        </span>
        ～
        <span class="date">
          {{ campaign.end_date|date:"Y-m-d" }}</span>
      </td>
      <td>
        <form action="{% url 'advertisement:ad_campaign_status' campaign.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="release-button release">
            公開中
          </button>
        </form>
      </td>
    </tr>
    {% endif %}
    {% empty %}
    <tr>
      <td colspan="7">データはありません。</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

viewy/templates/advertisement/stopped.html
{% extends 'advertisement/ad_campaigns_list.html' %}
{% load extra_filters %}
{% block table %}
<div class="sub-page-title">途中停止したキャンペーン</div>

<div class="filter">
  絞り込み：
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='achieved' %}" class="status-button">目標達成</a>
  <a href="{% url 'advertisement:close_ad_campaigns_list' %}" class="status-button" style="background-color: rgba(193, 193, 193, 0.76);">途中停止</a>
  <a href="{% url 'advertisement:filtered_ad_campaign_list' status='expired' %}" class="status-button">期限到達</a>
</div>
<div class="warning">※途中停止した時点での、実際の表示回数/クリック数に基づいて、CPM/CPCが再計算され料金が確定します
</div>
<div class="block">

  <table>
    <tr>
      <th>CPM/CPC</th>
      <th>キャンペーンタイトル</th>
      <th>広告数</th>
      <th>合計数/目標数</th>
      <th>料金 / 見積金額</th>
      <th>表示期間</th>
      <th>停止／公開</th>
    </tr>
    {% for campaign in campaigns %}
    {% if campaign.status == 'stopped' %}
    <tr class="release-campaign">
      <td>{{ campaign.pricing_model }}</td>
      <td>
        <a href="{% url 'advertisement:ad_campaign_detail' campaign.id %}" class="campaign-title">
          {{ campaign.title }}
        </a>
      </td>
      <td>{{ campaign.adinfos_count }}</td>
      <td class="views">
        {% if campaign.pricing_model == 'CPM' %}
        <span>{{ campaign.total_views_count|add_commas }}</span>
        <span>/{{ campaign.target_views|add_commas }}</span>
        {% elif campaign.pricing_model == 'CPC' %}
        <span>{{ campaign.total_clicks_count|add_commas }}</span>
        <span>/{{ campaign.target_clicks|add_commas }}</span>
        {% endif %}
      </td>
      <td>{{ campaign.fee|add_commas }} / {{ campaign.budget|add_commas }}</td>
      <td data-end-date="{{ campaign.end_date|date:" Y-m-d" }}" class="date-cell"><span class="date">
        {{ campaign.start_date|date:"Y-m-d" }}</span>～<br><span class="date">
          {{ campaign.end_date|date:"Y-m-d" }}</span></td>
      <td>
        <form>
          <button class="release-button stopped disabled-button">
            途中停止
          </button>
        </form>
      </td>
    </tr>
    {% endif %}
    {% empty %}
    <tr>
      <td colspan="7">データはありません。</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}