viewy/accounts/urls.py
from django.urls import path
from .views import (
  RegistUserView, InvitedRegistUserView, RegistAdvertiserView, UserLoginView, UserLogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetSendView, PasswordResetCompleteView, FollowView, EditPrfView,CheckAgeView, VerifyView, ResendVerificationCodeView, MessageListView, MessageDetailView, MessageDeleteView, SearchHistoryView, SearchHistorySaveView, HideSearchHistoriesView, DeleteUserView, ChangeDimensionView, FirstSettingView, SurveyAnswerView, SaveNotificationView, SaveFreezeNotificationView, BlockView, BlockPosterView, LoginAPIView, RegisterAPIView, SetCookieView,RegistEndView
)
from . import views

app_name = 'accounts'
urlpatterns = [ 
  path('regist/', RegistUserView.as_view(), name='regist'),  
  path('invited_regist/', InvitedRegistUserView.as_view(), name='invited_regist'),
  path('regist_advertiser/', RegistAdvertiserView.as_view(), name='regist_advertiser'),
  path('user_login/', UserLoginView.as_view(), name='user_login'),
  path('special_login/', UserLoginView.as_view(), name='special_login'),    
  path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
  path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
  path('password_reset_send/', PasswordResetSendView.as_view(), name='password_reset_send'),
  path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
  path('follow/<int:pk>/', FollowView.as_view(), name='follow'),
  path('block/<int:pk>/', BlockView.as_view(), name='block'),
  path('block_poster/<int:post_id>/', BlockPosterView.as_view(), name='block_poster'),
  path('edit_prf/', EditPrfView.as_view(), name='edit_prf'),
  path('check_age/', CheckAgeView.as_view(), name='check_age'),
  path('verify/', VerifyView.as_view(), name='verify'),
  path('resend_verification/', ResendVerificationCodeView.as_view(), name='resend_verification'),
  path('messages/', MessageListView.as_view(), name='message_list'),
  path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
  path('messages/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
  path('search_history/', views.SearchHistoryView.as_view(), name='search_history'),
  path('save_search_history/', views.SearchHistorySaveView.as_view(), name='save_search_history'),
  path('hide_search_histories/', views.HideSearchHistoriesView.as_view(), name='hide_search_histories'),
  path('delete_user/', DeleteUserView.as_view(), name='delete_user'),   
  path('change_dimension/', ChangeDimensionView.as_view(), name='change_dimension'),
  path('first_setting/', FirstSettingView.as_view(), name='first_setting'),
  path('survey_answer/<int:selected_option_id>/', SurveyAnswerView.as_view(), name='survey_answer'),
  path('save_notification_view/', SaveNotificationView.as_view(), name='save_notification_view'),
  path('save_freeze_notification_view/', SaveFreezeNotificationView.as_view(), name='save_freeze_notification_view'),
  path('login_api/', LoginAPIView.as_view(), name='login_api'),
  path('register_api/', RegisterAPIView.as_view(), name='login_api'),
  path('set_cookie/', SetCookieView.as_view(), name='set_cookie'),
  path('regist_end/', RegistEndView.as_view(), name='regist_end'),
]

viewy/management/urls.py
from django.urls import path
from .views import (Account, RecordUserStats, GetUserStats, UserAnalytics, DailyVisitorCountView, Partner, RandomRecommendedUsers, UpdateBoostTypeView, Post, Hashtag, Ad, UnapprovedAdsView, ApproveView, AffiliateCreateView, KanjiRegist, KanjiDelete, PosterWaiterList, AddToPosterGroup, RemoveFromWaitList, SearchEmailandAddPoster, ClickCountView, FreezeNotificationApproveView, DeleteFreezeNotificationView, PostSearch, TogglePostHiddenStatus, VideoListView, ToggleEncodingStatusView, CalculateMonthlyBilling)


app_name = 'management'
urlpatterns = [
  path('account/', Account.as_view(), name='account'),  
  path('record_user_stats/', RecordUserStats.as_view(), name='record_user_stats'),
  path('get_user_stats/', GetUserStats.as_view(), name='get_user_stats'),
  path('user_analytics/', UserAnalytics.as_view(), name='user_analytics'),
  path('analyze/', DailyVisitorCountView.as_view(), name='daily_visitor_count'),
  path('partner/', Partner.as_view(), name='partner'),  
  path('random-recommended-users/', RandomRecommendedUsers.as_view(), name='random_recommended_users'),
  path('update_boost_type/<int:user_id>/', UpdateBoostTypeView.as_view(), name='update_boost_type'),
  path('post/', Post.as_view(), name='post'),
  path('post_search/', PostSearch.as_view(), name='post_search'),
  path('toggle_post_hidden/<int:post_id>/', TogglePostHiddenStatus.as_view(), name='toggle_post_hidden'),
  path('hashtag/', Hashtag.as_view(), name='hashtag'),
  path('kanji_regist/', KanjiRegist.as_view(), name='kanji_regist'),
  path('kanji_delete/<int:pk>/', KanjiDelete.as_view(), name='kanji_delete'),
  path('ad/', Ad.as_view(), name='ad'),
  path('approve_ad/', UnapprovedAdsView.as_view(), name='approve_ad'),
  path('approve/<int:ad_id>/', ApproveView.as_view(), name='approve'),
  path('affiliate_create/', AffiliateCreateView.as_view(), name='affiliate_create'),
  path('poster_waiter_list/', PosterWaiterList.as_view(), name='poster_waiter_list'),
  path('add_to_poster_group/<int:user_id>/', AddToPosterGroup.as_view(), name='add_to_poster_group'),
  path('remove_from_wait_list/<int:user_id>/', RemoveFromWaitList.as_view(), name='remove_from_wait_list'),
  path('search_user/', SearchEmailandAddPoster.as_view(), name='search_user'),
  path('click_count/<str:name>/', ClickCountView.as_view(), name='click_count'),
  path('freeze_notification_approve/', FreezeNotificationApproveView.as_view(), name='freeze_notification_approve'),
  path('delete_freeze_notification/', DeleteFreezeNotificationView.as_view(), name='delete_freeze_notification'),
  path('video_list/', VideoListView.as_view(), name='video_list'),
   path('toggle-encoding-status/', ToggleEncodingStatusView.as_view(), name='toggle-encoding-status'),
  path('calculate_monthly_billing/', CalculateMonthlyBilling.as_view(), name='calculate_monthly_billing'),
]

viewy/posts/urls.py
from django.urls import path
from .views import (
 MangaCreateView, VisitorPostListView, PostListView, VideoCreateView, StarView, FavoriteView, RecommendPostView, GetRecommendUsers, FavoritePostListView, PosterPageView, HashtagPostListView, HashtagDimensionChangeView, HashtagPageView, FollowListView, FollowPageView, GetMoreFollowView, GetMorePreviousFollowView, GetMorePreviousCollectionView, DeleteCollectionView, RenameCollectionView, PosterPostListView, MyAccountView, SettingView, PinPostView, DeletePostView, AddPostView, SearchPageView, HotHashtagView, FavoritePageView, CollectionsMenuView, CollectionPageView, CollectionPostListView, GetMoreCollectionView, CreateNewCollection, BePartnerPageView, SubmitReportView, MyPostView, HiddenPostView, UnpublishedPostView, UpdateScheduledTimeView, AutoCorrectView, GetMorePostsView, GetMoreFavoriteView, GetMorePreviousFavoriteView, GetMorePosterPostsView, GetMorePreviousPosterPostsView, GetMoreHashtagView, GetMorePreviousHashtagView, AdsViewCount, WideAdsViewCount, AdsClickCount, WideAdsClickCount, AddToCollectionView, RemoveFromCollectionView, CreateCollectionAndAddPost, CollectionsForPostView, MyFollowListView, MyBlockListView, FreezeNotificationRequest, FreezeNotificationRequestSuccessView, FreezeListView, EmoteCountView, ViewDurationCountView, ShowMessageView, TestStreamingView, HandleEventParticipationView
)

app_name = 'posts'

urlpatterns = [
   path('manga_create/', MangaCreateView.as_view(), name='manga_create'),
   path('video_create/', VideoCreateView.as_view(), name='video_create'),
   path('postlist/', PostListView.as_view(), name='postlist'),
   path('visitor_postlist/', VisitorPostListView.as_view(), name='visitor_postlist'),
   path('get_more_posts/', GetMorePostsView.as_view(), name='get_more_posts'),
   path('star/', StarView.as_view(), name='star'),
   path('favorite/<int:pk>/', FavoriteView.as_view(), name='favorite'),
   path('recommend/', RecommendPostView.as_view(), name='recommend'),
   path('get_recommend_users/<int:post_id>/', GetRecommendUsers.as_view(), name='get_recommend_users'),
   path('fovorite_page/', FavoritePageView.as_view(), name='favorite_page'),
   path('fovorite_list/', FavoritePostListView.as_view(), name='favorite_list'),
   path('get_more_favorite/',  GetMoreFavoriteView.as_view(), name='get_more_favorite'),
   path('get_more_previous_favorite/',  GetMorePreviousFavoriteView.as_view(), name='get_more_previous_favorite'),
   path('collections_menu/', CollectionsMenuView.as_view(), name='collections_menu'),
   path('collection_page/<int:collection_id>/', CollectionPageView.as_view(), name='collection_page'),
   path('collection_list/<int:collection_id>/', CollectionPostListView.as_view(), name='collection_list'),
   path('get_more_collection/', GetMoreCollectionView.as_view(), name='get_more_collection'),
   path('get_more_previous_collection/', GetMorePreviousCollectionView.as_view(), name='get_more_previous_collection'),
   path('delete_collection/<int:collection_id>/', DeleteCollectionView.as_view(), name='delete_collection'),
   path('rename_collection/<int:collection_id>/', RenameCollectionView.as_view(), name='rename_collection'),
   path('create_new_collection/', CreateNewCollection.as_view(), name='create_new_collection'),
   path('hashtag_dimension_change/', HashtagDimensionChangeView.as_view(), name='hashtag_dimension_change'),
   path('hashtag/<str:hashtag>/', HashtagPageView.as_view(), name='hashtag'),
   path('hashtag_list/<str:hashtag>/', HashtagPostListView.as_view(), name='hashtag_list'),
   path('get_more_hashtag/', GetMoreHashtagView.as_view(), name='get_more_hashtag'),
   path('get_more_previous_hashtag/', GetMorePreviousHashtagView.as_view(), name='get_more_previous_hashtag'),
   path('posts/follow_list/', FollowListView.as_view(), name='follow_list'),
   path('follow_page/', FollowPageView.as_view(), name='follow_page'),
   path('get_more_follow/',  GetMoreFollowView.as_view(), name='get_more_follow'),
   path('get_more_previous_follow/',  GetMorePreviousFollowView.as_view(), name='get_more_previous_follow'),
   # path('back/', BackView.as_view(), name='back'),
   path('poster_page/<str:username>/', PosterPageView.as_view(), name='poster_page'),
   path('poster_post_list/<str:username>/', PosterPostListView.as_view(), name='poster_post_list'),
   path('get_more_poster_posts/',  GetMorePosterPostsView.as_view(), name='get_more_poster_posts'),
   path('get_more_previous_poster_posts/',  GetMorePreviousPosterPostsView.as_view(), name='get_more_previous_poster_posts'), 
   path('add_post/', AddPostView.as_view(), name='add_post'),
   path('my_account/', MyAccountView.as_view(), name='my_account'),   
   path('my_posts/', MyPostView.as_view(), name='my_posts'), 
   path('hidden_post/', HiddenPostView.as_view(), name='hidden_post'), 
   path('unpublished_post/', UnpublishedPostView.as_view(), name='unpublished_post'), 
   path('update_scheduled_time/', UpdateScheduledTimeView.as_view(), name='update_scheduled_time'),
   path('my_follow_list/', MyFollowListView.as_view(), name='my_follow_list'),
   path('block-list/', MyBlockListView.as_view(), name='block_list'),
   path('freeze_notification_request/', FreezeNotificationRequest.as_view(), name='freeze_notification_request'),
   path('freeze_notification_request_success/', FreezeNotificationRequestSuccessView.as_view(), name='freeze_notification_request_success'),
   path('freeze-list/', FreezeListView.as_view(), name='freeze_list'),
   path('pin_post/', PinPostView.as_view(), name='pin_post'),
   path('delete_post/', DeletePostView.as_view(), name='delete_post'),
   path('setting/', SettingView.as_view(), name='setting'),   
   path('searchpage/', SearchPageView.as_view(), name='searchpage'),
   path('hothashtag/', HotHashtagView.as_view(), name='hothashtag'),
   path('auto_correct/', AutoCorrectView.as_view(), name='auto_correct'),
   path('be_partner/', BePartnerPageView.as_view(), name='be_partner'),
   path('ads_view_count/<int:ad_id>', AdsViewCount.as_view(), name='ads_view_count'),
   path('wideads_view_count/<int:ad_id>', WideAdsViewCount.as_view(), name='wideads_view_count'),
   path('ads_click_count/<int:ad_id>', AdsClickCount.as_view(), name='ads_click_count'),
   path('wideads_click_count/<int:ad_id>', WideAdsClickCount.as_view(), name='Wideads_click_count'),
   path('add_to_collection/', AddToCollectionView.as_view(), name='add_to_collection'),
   path('remove_from_collection/', RemoveFromCollectionView.as_view(), name='remove_from_collection'),
   path('create_collection_and_add_post/', CreateCollectionAndAddPost.as_view(), name='create_collection_and_add_post'),
   path('get_collections_for_post/<int:post_id>/', CollectionsForPostView.as_view(), name='get_collections_for_post'),
   path('report/', SubmitReportView.as_view(), name='report'),
   path('emote_count/<int:post_id>/<int:emote_number>/', EmoteCountView.as_view(), name='emote_count'),
   path('view_duration_count/', ViewDurationCountView.as_view(), name='view_duration_count'),
   path('show_message/', ShowMessageView.as_view(), name='show_message'),
   path('test_streaming/', TestStreamingView.as_view(), name='test_streaming'),
   path('handle_event_participation/', HandleEventParticipationView.as_view(), name='handle_event_participation'),
]

viewy/management/forms.py
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import Users
from posts.models import RecommendedUser, Posts
from advertisement.models import AdCampaigns, AdInfos

class HashTagSearchForm(forms.Form):
    hashtag1 = forms.CharField(max_length=30, label=False, widget=forms.TextInput(attrs={'placeholder': 'ハッシュタグ１'}))
    hashtag2 = forms.CharField(max_length=30, label=False, widget=forms.TextInput(attrs={'placeholder': 'ハッシュタグ２'}))
    hashtag3 = forms.CharField(max_length=30, label=False, widget=forms.TextInput(attrs={'placeholder': 'ハッシュタグ３'}))
    hashtag4 = forms.CharField(max_length=30, label=False, widget=forms.TextInput(attrs={'placeholder': 'ハッシュタグ４'}))

class RecommendedUserForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i in range(1, 13):
            self.fields[f'user{i}'] = forms.CharField(label=str(i), max_length=255)  # Change to CharField

    def clean(self):
        cleaned_data = super().clean()
        user_list = [cleaned_data.get(f"user{i}") for i in range(1, 13)]

        if len(user_list) != len(set(user_list)):
            raise forms.ValidationError("同じユーザーネームを重複して選択することはできません。")

        # Check if each username exists in the database
        for i, username in enumerate(user_list, start=1):
            if not Users.objects.filter(username=username).exists():
                self.add_error(f'user{i}', f"ユーザーネーム '{username}' は存在しません。")
    # Add an error for non-existing usernames

        return cleaned_data
    
    
class BoostTypeForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['boost_type']
        
        
class AffiliateInfoForm(forms.ModelForm):
    ad_campaign = forms.ModelChoiceField(queryset=AdCampaigns.objects.none(), label='Ad Campaign')

    class Meta:
        model = AdInfos
        fields = ['ad_campaign']

    def __init__(self, *args, **kwargs):
        super(AffiliateInfoForm, self).__init__(*args, **kwargs)
        
        # affiliate@gmail.comのユーザーを取得
        affiliate_user = Users.objects.get(email='affiliate@gmail.com')
        
        # そのユーザーが作成したキャンペーンのみをフィルタリングして選択できるように設定
        self.fields['ad_campaign'].queryset = AdCampaigns.objects.filter(created_by=affiliate_user)
        
        
class AffiliateForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', widget=forms.TextInput(attrs={'placeholder': 'タイトル（最大30字）'}))
    hashtag1 = forms.CharField(required=False, label='ハッシュタグ１', widget=forms.TextInput(attrs={'placeholder': '（最大20字）'}), error_messages={'max_length': "ハッシュタグは最大20字までです。",})
    hashtag2 = forms.CharField(required=False, label='ハッシュタグ２', widget=forms.TextInput(attrs={'placeholder': ''}), error_messages={'max_length': "ハッシュタグは最大20字までです。",})
    hashtag3 = forms.CharField(required=False, label='ハッシュタグ３', widget=forms.TextInput(attrs={'placeholder': ''}), error_messages={'max_length': "ハッシュタグは最大20字までです。",})
    caption = forms.CharField(required=False, label='説明欄', widget=forms.Textarea(attrs={'placeholder': 'キャプション（最大100字）'}))
    affiliate_tag = forms.CharField(
        required=False, 
        label='アフィリエイトタグ', 
        widget=forms.Textarea(attrs={'placeholder': 'アフィリエイトタグを入力'})  # ここを変更
    )

    class Meta:
        model = Posts
        fields = ['title', 'hashtag1', 'hashtag2', 'hashtag3', 'caption', 'affiliate_tag']
        
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        caption = cleaned_data.get('caption')
        
        # タイトルとキャプションの内容が重複する場合はエラー
        if title == caption:
            raise ValidationError("タイトルとキャプションの内容は重複できません。")
        
        # タイトルが2文字以下の場合はエラー
        if len(title) < 2:
            raise ValidationError("タイトルは2文字以上で入力してください。")
        
        return cleaned_data
    
class AnalyzeDateForm(forms.Form):
    analyze_date = forms.DateField(label="Analysis Date", widget=forms.DateInput(attrs={'type': 'date'}))

viewy/templates/management/analyze_visitor.html
{% extends 'management/management_base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/management/ad.css' %}">
{% endblock %}


{% block content %}


<div class="block">
<!-- analyze_visitor.html -->
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Analyze</button>
</form>
</div>


{% endblock %}

viewy/templates/management/click_count.html
{% extends 'management/management_base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/management/click_count.css' %}">
{% endblock %}


{% block content %}


<div class="block">

</div>


{% endblock %}

viewy/templates/management/monthly_billing.html
{% extends 'management/management_base.html' %}
{% load static %}

{% block content %}


<div class="block">
  <div>月末広告計算</div>

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <form method="post" action="{% url 'management:calculate_monthly_billing' %}">
    {% csrf_token %}
    <label for="billing_date">Billing Date:</label>
    <input type="datetime-local" id="billing_date" name="billing_date">
    <input type="submit" value="Calculate Monthly Billing">
  </form>
</div>


{% endblock %}

viewy/templates/management/partner.html
{% extends 'management/management_base.html' %}
{% load static %}
{% block head %}
{% endblock %}


{% block content %}

<div class="flex">
  <div class="block total_table flex">
    <div class="total_title">総パートナー数：</div>
    <div class="total_number">{{ poster_users_count }}</div>
  </div>
  
  <div class="block total_table flex" style="margin-left: 16px;">
    <div class="total_title">３次元パートナー数：</div>
    <div class="total_number">{{ real_posters_count }}</div>
  </div>
  
  <div class="block total_table flex" style="margin-left: 16px;">
    <div class="total_title">２次元パートナー数：</div>
    <div class="total_number">{{ not_real_posters_count }}</div>
  </div>

  <div class="block total_table flex" style="margin-left: 16px;">
    <div class="total_title">一週間内に来たパートナー数：</div>
    <div class="total_number">{{ active_posters_count }}</div>
  </div>
</div>


<div class="flex">
  <div class="block scroll partner">

    <table>
      <tr>
        <th>パートナー</th>
        <th>表示名</th>
        <th>フォロワー</th>
        <th>Sフォロワー</th>
        <th>投稿数</th>
        <th>視聴回数</th>
        <th>S視聴回数</th>
        <th>平均QP</th>
        <th>ブースト</th>
      </tr>
      {% for user in users %}
      <tr class="{% if not user.is_real %}not-real{% endif %}">
        <td>{{ user.username }}</td>
        <td>
          {% if user in active_posters %}
          <span class="active-dot"></span>
          {% endif %}
          {{ user.displayname }}
        </td>
        <td>{{ user.follow_count }}</td>
        <td>{{ user.support_follow_count}}</td>
        <td>{{ user.total_posts }}</td>
        <td>{{ user.total_views }}</td>
        <td>{{ user.total_support_views|floatformat:"0" }}</td>
        <td>{{ user.avg_qp|floatformat:2 }}</td>
        <td>
          <form method="post" action="{% url 'management:update_boost_type' user.id %}" class="boostTypeForm" data-user-id="{{ user.id }}">
            {% csrf_token %}
            <select class="{% if user.boost_type == 'normal' %}normal{% elif user.boost_type == 'firstboost' %}first-boost{% elif user.boost_type == 'boost' %}boost{% elif user.boost_type == 'superboost' %}super-boost{% elif user.boost_type == 'viewyboost' %}viewy-boost{% endif %} boostTypeSelect" name="boost_type">
              <option value="normal" {% if user.boost_type == 'normal' %}selected{% endif %}>Normal</option>
              <option class="first-boost" value="firstboost" {% if user.boost_type == 'firstboost' %}selected{% endif %}>First Boost</option>
              <option class="boost" value="boost" {% if user.boost_type == 'boost' %}selected{% endif %}>Boost</option>
              <option class="super-boost" value="superboost" {% if user.boost_type == 'superboost' %}selected{% endif %}>Super Boost</option>
              <option class="viewy-boost" value="viewyboost" {% if user.boost_type == 'viewyboost' %}selected{% endif %}>Viewy Boost</option>
            </select>
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
  
  </div>
  
  <div class="block hot-partner">おすすめユーザー設定
    <form method="post">
      {% csrf_token %}
  
      {% if error_message %}
      <div class="error">
        {{ error_message }}
      </div>
      {% endif %}
  
      {% if form.non_field_errors %}
      <div class="error">
        {{ form.non_field_errors }}
      </div>
      {% endif %}
  
      {% for field in form %}
      <div class="field-wrapper partner-input">
        {{ field.errors }} <!-- ここでフィールドのエラーを表示 -->
        {{ field.label_tag }}
        {{ field }}
      </div>
      {% endfor %}
  
      <div class="flex">
        <button id="setRandomUsersBtn" class="random">ランダムで選択</button>
        <button type="submit" class="submit">設定</button>
      </div>

    </form>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

$(document).ready(function() {
    $('.boostTypeSelect').change(function() {
        var form = $(this).closest('form');
        var url = form.attr('action');
        var data = form.serialize(); // フォーム内の全データをシリアライズ

        $.ajax({
            type: 'POST',
            url: url,
            data: data,
            success: function(response) {
                console.log('Success:', response);
            },
            error: function(error) {
                console.log('Error:', error);
            }
        });
    });
});
</script>
<script>
  $('#setRandomUsersBtn').on('click', function(e) {
      e.preventDefault();  // ボタンのデフォルトの動作を停止

      // DjangoのビューへのAjaxリクエストを作成
      $.ajax({
          url: '{% url "management:random_recommended_users" %}',
          type: 'GET',
          success: function(data) {
              // サーバーからのレスポンスを利用して、フォームフィールドを更新
              for (let i = 1; i <= 12; i++) {
                  $(`#id_user${i}`).val(data.users[i - 1].username);
              }
          }
      });
  });
</script>
{% endblock %}

viewy/templates/management/post_search.html
{% extends 'management/management_base.html' %}
{% load static %}
{% block head %}

{% endblock %}


{% block content %}

<div class="flex">

  <form method="get" action="">
    <input type="text" name="q" value="{{ request.GET.q }}" placeholder="usernameまたはdisplayname">
    <button type="submit">Search</button>
  </form>

  {% if error_message %}
  <div>{{ error_message }}</div>
  {% endif %}

  <div>
    {% for post in posts %}
    <div>
      <div>{{ post.title }}</div>
      <span>
        is_hidden:
        <a href="{% url 'management:toggle_post_hidden' post.id %}?q={{ request.GET.q }}">
          {{ post.is_hidden }}
        </a>
      </span>
    </div>
    {% endfor %}
  </div>

</div>


{% endblock %}

viewy/templates/management/poster_waiter.html
{% extends 'management/management_base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/management/poster_waiter.css' %}">
{% endblock %}


{% block content %}

<div class="block">
  <table class="wait-table">
    <thead>
        <tr>
            <th>ユーザーネーム</th>
            <th>Email</th>
            <th>３次元</th>
            <th>２次元</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        {% for user in object_list %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td class="center">
                    <a href="{% url 'management:add_to_poster_group' user.id %}?is_real=true" onclick="return confirm('{{ user.username }}を３次元のクリエイターとしてポスターグループに追加しますか？ユーザーネームをもう一度確認してください');" class="is-real">３次元として追加</a>
                </td>
                <td class="center">
                    <a href="{% url 'management:add_to_poster_group' user.id %}?is_real=false" onclick="return confirm('{{ user.username }}を２次元のクリエイターとしてポスターグループに追加しますか？ユーザーネームをもう一度確認してください');" class="not-real">２次元として追加</a>
                </td>
                <td class="center"><a href="{% url 'management:remove_from_wait_list' user.id %}" onclick="return confirm('{{ user.username }}をリストから削除しますか？ユーザーネームをもう一度確認してください');" class="delete-button">削除</a></td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">特別なユーザーが見つかりません。</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>



</div>





{% endblock %}