viewy/posts/urls.py
from django.urls import path
from .views import (
 MangaCreateView, VisitorPostListView, PostListView, VideoCreateView, StarView, FavoriteView, RecommendPostView, GetRecommendUsers, FavoritePostListView, PosterPageView, HashtagPostListView, HashtagDimensionChangeView, HashtagPageView, FollowListView, FollowPageView, GetMoreFollowView, GetMorePreviousFollowView, GetMorePreviousCollectionView, DeleteCollectionView, RenameCollectionView, PosterPostListView, MyAccountView, SettingView, PinPostView, DeletePostView, AddPostView, SearchPageView, HotHashtagView, FavoritePageView, CollectionsMenuView, CollectionPageView, CollectionPostListView, GetMoreCollectionView, CreateNewCollection, BePartnerPageView, SubmitReportView, MyPostView, HiddenPostView, UnpublishedPostView, UpdateScheduledTimeView, AutoCorrectView, GetMorePostsView, GetMoreFavoriteView, GetMorePreviousFavoriteView, GetMorePosterPostsView, GetMorePreviousPosterPostsView, GetMoreHashtagView, GetMorePreviousHashtagView, AdsViewCount, WideAdsViewCount, AdsClickCount, WideAdsClickCount, AddToCollectionView, RemoveFromCollectionView, CreateCollectionAndAddPost, CollectionsForPostView, MyFollowListView, MyBlockListView, FreezeNotificationRequest, FreezeNotificationRequestSuccessView, FreezeListView, EmoteCountView, ViewDurationCountView, ShowMessageView, TestStreamingView, HandleEventParticipationView
)

app_name = 'posts'

urlpatterns = [
   path('manga_create/', MangaCreateView.as_view(), name='manga_create'),
   path('video_create/', VideoCreateView.as_view(), name='video_create'),
   path('postlist/', PostListView.as_view(), name='postlist'),
   path('visitor_postlist/', VisitorPostListView.as_view(), name='visitor_postlist'),
   path('get_more_posts/', GetMorePostsView.as_view(), name='get_more_posts'),
   path('star/', StarView.as_view(), name='star'),
   path('favorite/<int:pk>/', FavoriteView.as_view(), name='favorite'),
   path('recommend/', RecommendPostView.as_view(), name='recommend'),
   path('get_recommend_users/<int:post_id>/', GetRecommendUsers.as_view(), name='get_recommend_users'),
   path('fovorite_page/', FavoritePageView.as_view(), name='favorite_page'),
   path('fovorite_list/', FavoritePostListView.as_view(), name='favorite_list'),
   path('get_more_favorite/',  GetMoreFavoriteView.as_view(), name='get_more_favorite'),
   path('get_more_previous_favorite/',  GetMorePreviousFavoriteView.as_view(), name='get_more_previous_favorite'),
   path('collections_menu/', CollectionsMenuView.as_view(), name='collections_menu'),
   path('collection_page/<int:collection_id>/', CollectionPageView.as_view(), name='collection_page'),
   path('collection_list/<int:collection_id>/', CollectionPostListView.as_view(), name='collection_list'),
   path('get_more_collection/', GetMoreCollectionView.as_view(), name='get_more_collection'),
   path('get_more_previous_collection/', GetMorePreviousCollectionView.as_view(), name='get_more_previous_collection'),
   path('delete_collection/<int:collection_id>/', DeleteCollectionView.as_view(), name='delete_collection'),
   path('rename_collection/<int:collection_id>/', RenameCollectionView.as_view(), name='rename_collection'),
   path('create_new_collection/', CreateNewCollection.as_view(), name='create_new_collection'),
   path('hashtag_dimension_change/', HashtagDimensionChangeView.as_view(), name='hashtag_dimension_change'),
   path('hashtag/<str:hashtag>/', HashtagPageView.as_view(), name='hashtag'),
   path('hashtag_list/<str:hashtag>/', HashtagPostListView.as_view(), name='hashtag_list'),
   path('get_more_hashtag/', GetMoreHashtagView.as_view(), name='get_more_hashtag'),
   path('get_more_previous_hashtag/', GetMorePreviousHashtagView.as_view(), name='get_more_previous_hashtag'),
   path('posts/follow_list/', FollowListView.as_view(), name='follow_list'),
   path('follow_page/', FollowPageView.as_view(), name='follow_page'),
   path('get_more_follow/',  GetMoreFollowView.as_view(), name='get_more_follow'),
   path('get_more_previous_follow/',  GetMorePreviousFollowView.as_view(), name='get_more_previous_follow'),
   # path('back/', BackView.as_view(), name='back'),
   path('poster_page/<str:username>/', PosterPageView.as_view(), name='poster_page'),
   path('poster_post_list/<str:username>/', PosterPostListView.as_view(), name='poster_post_list'),
   path('get_more_poster_posts/',  GetMorePosterPostsView.as_view(), name='get_more_poster_posts'),
   path('get_more_previous_poster_posts/',  GetMorePreviousPosterPostsView.as_view(), name='get_more_previous_poster_posts'), 
   path('add_post/', AddPostView.as_view(), name='add_post'),
   path('my_account/', MyAccountView.as_view(), name='my_account'),   
   path('my_posts/', MyPostView.as_view(), name='my_posts'), 
   path('hidden_post/', HiddenPostView.as_view(), name='hidden_post'), 
   path('unpublished_post/', UnpublishedPostView.as_view(), name='unpublished_post'), 
   path('update_scheduled_time/', UpdateScheduledTimeView.as_view(), name='update_scheduled_time'),
   path('my_follow_list/', MyFollowListView.as_view(), name='my_follow_list'),
   path('block-list/', MyBlockListView.as_view(), name='block_list'),
   path('freeze_notification_request/', FreezeNotificationRequest.as_view(), name='freeze_notification_request'),
   path('freeze_notification_request_success/', FreezeNotificationRequestSuccessView.as_view(), name='freeze_notification_request_success'),
   path('freeze-list/', FreezeListView.as_view(), name='freeze_list'),
   path('pin_post/', PinPostView.as_view(), name='pin_post'),
   path('delete_post/', DeletePostView.as_view(), name='delete_post'),
   path('setting/', SettingView.as_view(), name='setting'),   
   path('searchpage/', SearchPageView.as_view(), name='searchpage'),
   path('hothashtag/', HotHashtagView.as_view(), name='hothashtag'),
   path('auto_correct/', AutoCorrectView.as_view(), name='auto_correct'),
   path('be_partner/', BePartnerPageView.as_view(), name='be_partner'),
   path('ads_view_count/<int:ad_id>', AdsViewCount.as_view(), name='ads_view_count'),
   path('wideads_view_count/<int:ad_id>', WideAdsViewCount.as_view(), name='wideads_view_count'),
   path('ads_click_count/<int:ad_id>', AdsClickCount.as_view(), name='ads_click_count'),
   path('wideads_click_count/<int:ad_id>', WideAdsClickCount.as_view(), name='Wideads_click_count'),
   path('add_to_collection/', AddToCollectionView.as_view(), name='add_to_collection'),
   path('remove_from_collection/', RemoveFromCollectionView.as_view(), name='remove_from_collection'),
   path('create_collection_and_add_post/', CreateCollectionAndAddPost.as_view(), name='create_collection_and_add_post'),
   path('get_collections_for_post/<int:post_id>/', CollectionsForPostView.as_view(), name='get_collections_for_post'),
   path('report/', SubmitReportView.as_view(), name='report'),
   path('emote_count/<int:post_id>/<int:emote_number>/', EmoteCountView.as_view(), name='emote_count'),
   path('view_duration_count/', ViewDurationCountView.as_view(), name='view_duration_count'),
   path('show_message/', ShowMessageView.as_view(), name='show_message'),
   path('test_streaming/', TestStreamingView.as_view(), name='test_streaming'),
   path('handle_event_participation/', HandleEventParticipationView.as_view(), name='handle_event_participation'),
]

viewy/support/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import DynamicTemplateView, InquiryFormView, InquirySuccessView

app_name = 'support'


urlpatterns = [
  path('', TemplateView.as_view(template_name='support/first.html'), name='first'),
  path('inquiry_form/', InquiryFormView.as_view(), name='inquiry_form'),
  path('inquiry_success/', InquirySuccessView.as_view(), name='inquiry_success'),
  path('<str:pretitle>/<str:title>/<str:subtitle>/', DynamicTemplateView.as_view(), name='subtitle_page'),
  path('<str:pretitle>/<str:title>/', DynamicTemplateView.as_view(), name='title_page'),
  path('<str:pretitle>/', DynamicTemplateView.as_view(), name='pretitle_page'),
]

viewy/support/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.http import HttpResponse
from .forms import BaseInquiryForm, NormalInquiryForm, CorporateInquiryForm
from django.shortcuts import redirect
from django.db import transaction
from django.core.mail import EmailMessage
from .models import NormalInquiry, CorporateInquiry

class DynamicTemplateView(TemplateView):
    def get_template_names(self):
        pretitle = self.kwargs.get('pretitle')
        title = self.kwargs.get('title')
        subtitle = self.kwargs.get('subtitle')

        # 3つのパラメーターが指定された場合
        if pretitle and title and subtitle:
            return [f'support/{pretitle}/{title}/{subtitle}.html']

        # 2つのパラメーターが指定された場合
        if pretitle and title:
            return [f'support/{pretitle}/{title}/index.html']  # ここを変更

        # 1つのパラメーターが指定された場合
        if pretitle:
            return [f'support/{pretitle}/index.html']

        # パラメーターが指定されていない場合
        return ['support/first.html']


class InquiryFormView(View):
    def get(self, request, *args, **kwargs):
        base_form = BaseInquiryForm()
        normal_form = NormalInquiryForm()
        corporate_form = CorporateInquiryForm()
        return render(request, 'support/inquiry_form.html', {
            'base_form': base_form,
            'normal_form': normal_form,
            'corporate_form': corporate_form,
        })

    def send_inquiry_notification(self, inquiry_instance):
        # メールの件名を設定
        subject = f'{inquiry_instance.name}様からのお問い合わせ'

        # メッセージの本文を組み立てる
        message_parts = [
            '以下の内容でお問い合わせがありました。',
            '--------------------------------',
            f'お問い合わせ種類: {"一般" if inquiry_instance.inquiry_type == "normal" else "法人"}',
            f'氏名: {inquiry_instance.name}様',
            f'メールアドレス: {inquiry_instance.email}',
            f'件名: {inquiry_instance.subject}',
            f'内容:',
            f'{inquiry_instance.content}',
            '--------------------------------',
        ]

        # NormalInquiry の場合の追加情報
        if isinstance(inquiry_instance, NormalInquiry):
            message_parts.extend([
                '追加情報:',
                f'発生日時: {inquiry_instance.occurrence_date.strftime("%Y-%m-%d %H:%M")}',
                f'発生URL: {inquiry_instance.occurrence_url}',
                f'機種: {inquiry_instance.device}',
                f'ブラウザ: {inquiry_instance.browser}',
            ])

        # CorporateInquiry の場合の追加情報
        elif isinstance(inquiry_instance, CorporateInquiry):
            message_parts.extend([
                '追加情報:',
                f'会社名: {inquiry_instance.company_name}様',
                f'所属部署名: {inquiry_instance.department_name if inquiry_instance.department_name else "情報なし"}',
            ])

        # メッセージ本文を改行で結合
        message = "\n".join(message_parts)

        # メールの送信者
        from_email = 'お問い合わせ <inquiry@viewy.net>'

        # メールの受信者
        recipient_list = ['support@viewy.net']


        # EmailMessage オブジェクトの作成
        email = EmailMessage(
            subject=subject,
            body=message,
            from_email=from_email,
            to=recipient_list,
            headers={'Reply-To': inquiry_instance.email}  # Reply-To ヘッダを追加
        )

        # メールの送信
        try:
            email.send()
            print("メールが正常に送信されました。")
        except Exception as e:
            print(f"メール送信中にエラーが発生しました: {e}")

    def send_confirmation_email(self, inquiry_instance):
        subject = 'お問い合わせありがとうございます'
        # メッセージの本文を組み立てる
        message_parts = [
            f"{inquiry_instance.name}様\n\n",
            "このたびは、お問い合わせいただきありがとうございます。\n",
            "弊社営業時間内に、いただきましたお問い合わせをご確認いたします。\n",
            "※お問い合わせの内容によっては、回答に時間がかかる場合や回答できない場合があります。\n\n\n",
            "[お問合せ内容]\n\n",
            f"■お名前\n{inquiry_instance.name}\n",
            f"■メールアドレス\n{inquiry_instance.email}\n",
            f"■件名\n{inquiry_instance.subject}\n",
            f"■お問い合わせ内容\n{inquiry_instance.content}\n",
        ]

        # NormalInquiry の場合の追加情報
        if isinstance(inquiry_instance, NormalInquiry):
            message_parts.extend([
                f"■発生日時: {inquiry_instance.occurrence_date.strftime('%Y-%m-%d %H:%M')}\n",
                f"■発生URL: {inquiry_instance.occurrence_url}\n",
                f"■機種: {inquiry_instance.device}\n",
                f"■ブラウザ: {inquiry_instance.browser}\n\n",
            ])

        # CorporateInquiry の場合の追加情報
        elif isinstance(inquiry_instance, CorporateInquiry):
            message_parts.extend([
                f"■会社名: {inquiry_instance.company_name}\n",
                f"■所属部署名: {inquiry_instance.department_name if inquiry_instance.department_name else '情報なし'}\n\n",
            ])

        # 追加のフッター情報
        message_parts.append(
            "------------------------------\n"
            "Viewy：https://www.viewy.net\n"
            "MAIL：support@viewy.net\n"
            "運営：合同会社Front&Front\n"
            "※営業時間：10:00～18:00 （土日・祝日は除く）\n"
            "Front&Front ホームページ：http://front-front.com/\n"
            "------------------------------\n\n"
            "このメールは送信専用のメールアドレスから送信されているため、返信できません。\n"
            "このメールに心当たりがない場合や、ご不明な点がございましたら、\n"
            "support@viewy.net までご連絡ください。"
        )

        # メッセージ本文を改行で結合
        message = "".join(message_parts)
        from_email = 'Viewyお問い合わせ <inquiry-conf@viewy.net>'
        recipient_list = [inquiry_instance.email]

        # EmailMessage オブジェクトの作成
        email = EmailMessage(
            subject=subject,
            body=message,
            from_email=from_email,
            to=recipient_list
        )

        # メールの送信
        try:
            email.send()
            print("お客様へ確認メールが正常に送信されました。")
        except Exception as e:
            print(f"確認メール送信中にエラーが発生しました: {e}")

    def post(self, request, *args, **kwargs):
        base_form = BaseInquiryForm(request.POST)
        normal_form = NormalInquiryForm(request.POST)
        corporate_form = CorporateInquiryForm(request.POST)

        if base_form.is_valid():
            inquiry_type = base_form.cleaned_data['inquiry_type']

            # トランザクションを使用してデータの整合性を保証
            with transaction.atomic():
                if inquiry_type == 'normal':
                    if normal_form.is_valid():
                        normal_inquiry = normal_form.save(commit=False)
                        normal_inquiry.name = base_form.cleaned_data['name']
                        normal_inquiry.email = base_form.cleaned_data['email']
                        normal_inquiry.inquiry_type = inquiry_type
                        normal_inquiry.subject = normal_form.cleaned_data['normal_subject']
                        normal_inquiry.content = normal_form.cleaned_data['normal_content']
                        normal_inquiry.save()
                        self.send_inquiry_notification(normal_inquiry)
                        self.send_confirmation_email(normal_inquiry)
                        return redirect('support:inquiry_success')
                    else:
                        # 通常の問い合わせフォームのバリデーションエラーを表示
                        print("Normal Inquiry Form Errors:", normal_form.errors)

                elif inquiry_type == 'corporate':
                    if corporate_form.is_valid():
                        corporate_inquiry = corporate_form.save(commit=False)
                        corporate_inquiry.name = base_form.cleaned_data['name']
                        corporate_inquiry.email = base_form.cleaned_data['email']
                        corporate_inquiry.inquiry_type = inquiry_type
                        corporate_inquiry.subject = corporate_form.cleaned_data['corporate_subject']
                        corporate_inquiry.content = corporate_form.cleaned_data['corporate_content']
                        corporate_inquiry.save()
                        self.send_inquiry_notification(corporate_inquiry)
                        self.send_confirmation_email(corporate_inquiry)
                        return redirect('support:inquiry_success')
                    else:
                        # 法人問い合わせフォームのバリデーションエラーを表示
                        print("Corporate Inquiry Form Errors:", corporate_form.errors)

        else:
            # ベースフォームのバリデーションエラーを表示
            print("Base Inquiry Form Errors:", base_form.errors)

        # バリデーションに失敗した場合、フォームを再度表示
        return render(request, 'support/inquiry_form.html', {
            'base_form': base_form,
            'normal_form': normal_form,
            'corporate_form': corporate_form,
        })

class InquirySuccessView(TemplateView):
    template_name = 'support/inquiry_success.html'

viewy/templates/support/detail_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/support/support_base.css' %}">
  <!-- iOS向けの指定 -->
  <!-- <link rel="apple-touch-icon" type="image/png" href="{{ MEDIA_URL }}icon_management/apple-touch-icon.png" sizes="180x180"> -->
  <script src="https://kit.fontawesome.com/ad23325601.js" crossorigin="anonymous"></script>
  <title>Viewy-Support</title>
  {% block head %}
  {% endblock %}
</head>

<body>
  <header>
    <div class="nav-container">
      <div class="nav-item logo">
        <a href="{% url 'support:first'%}">
          <img src="{{ MEDIA_URL }}others\ヘッダー2.png" alt="Home">
        </a>
      </div>
      <div class="nav-right">
        <div class="nav-item"><a class="a-link" href="{% url 'support:inquiry_form'%}">お問い合わせ</a></div>
        <div class="nav-item viewy"><a class="a-link" href="{% url 'posts:postlist'%}">Viewyへ</a></div>
      </div>
    </div>
  </header>
  <div class="main">
    <div class="accordion">
      <div class="accordion-item">
        <div class="accordion-header pretitle" data-pretitle="about_viewy">
          <a href="{% url 'support:pretitle_page' pretitle='about_viewy' %}">Viewyについて</a>
          <i class="fas fa-chevron-down"></i>
        </div>
        <div class="accordion-content">

          <div class="n-accordion">
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='about_viewy' title='use' %}">Viewyの利用方法</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='about_viewy' title='use' subtitle='viewy' %}">Viewyは安全なサイトですか</a></div>
              </div>

            </div>
            <div class="n-accordion-item">
              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='about_viewy' title='regist_login' %}">アカウント作成・ログイン</a>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='about_viewy' title='regist_login' subtitle='regist' %}">アカウント作成</a></div>
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='about_viewy' title='regist_login' subtitle='n_login' %}">ログインできない</a></div>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="accordion-item">
        <div class="accordion-header pretitle" data-pretitle="user">
          <a href="{% url 'support:pretitle_page' pretitle='user' %}">ユーザー</a>
          <i class="fas fa-chevron-down"></i>
        </div>
        <div class="accordion-content">

          <div class="n-accordion">
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='user' title='function' %}">各種機能</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='user' title='function' subtitle='collection' %}">コレクション機能</a></div>
              </div>

            </div>
            <div class="n-accordion-item">
              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='user' title='error' %}">閲覧時のエラー</a>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='user' title='error' subtitle='n_view' %}">投稿が視聴できません</a></div>
              </div>
            </div>
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='user' title='campaign' %}">キャンペーン</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='user' title='campaign' subtitle='fee' %}">キャンペーンとは何ですか</a></div>
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='user' title='campaign' subtitle='join' %}">どのように参加すればいいですか</a></div>
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='user' title='campaign' subtitle='winning' %}">当選を確認したい</a></div>
              </div>

            </div>

          </div>
        </div>
      </div>
      <div class="accordion-item">
        <div class="accordion-header pretitle" data-pretitle="partner">
          <a href="{% url 'support:pretitle_page' pretitle='partner' %}">パートナー</a>
          <i class="fas fa-chevron-down"></i>
        </div>
        <div class="accordion-content">

          <div class="n-accordion">
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='partner' title='regist' %}">パートナー登録</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='partner' title='regist' subtitle='who' %}">誰でもパートナーになれますか</a></div>
              </div>

            </div>
            <div class="n-accordion-item">
              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='partner' title='post' %}">投稿</a>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='partner' title='post' subtitle='img' %}">画像を投稿</a></div>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='partner' title='post' subtitle='img_error' %}">画像を投稿できない</a></div>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='partner' title='post' subtitle='video' %}">動画を投稿</a></div>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a  href="{% url 'support:subtitle_page' pretitle='partner' title='post' subtitle='video_error' %}">動画を投稿できない</a></div>
              </div>
            </div>
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='partner' title='account_page' %}">アカウントページ</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='partner' title='account_page' subtitle='mypost' %}">自分の投稿を確認・ピン留め・削除したい</a></div>
              </div>

            </div>

          </div>
        </div>
      </div>
      <div class="accordion-item">
        <div class="accordion-header pretitle" data-pretitle="service">
          <a href="{% url 'support:pretitle_page' pretitle='service' %}">サービス全般</a>
          <i class="fas fa-chevron-down"></i>
        </div>
        <div class="accordion-content">

          <div class="n-accordion">
            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='service' title='general' %}">一般情報</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='service' title='general' subtitle='campany' %}">運営会社</a></div>
              </div>
              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='service' title='general' subtitle='term' %}">規約</a></div>
              </div>

            </div>

            <div class="n-accordion-item">

              <div class="n-accordion-header title">
                <a  href="{% url 'support:title_page' pretitle='service' title='amusement' %}">風営法</a>
              </div>

              <div class="n-accordion-content">
                <div class="subtitle"><a href="{% url 'support:subtitle_page' pretitle='service' title='amusement' subtitle='notification' %}">映像送信型性風俗特殊営業の届出</a></div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="topic">
      {% block topic %}
      {% endblock %}
    </div>

  </div>
  <footer class="footer">
    <div><a href="{% url 'support:first'%}">Viewy Support</a></div>
  </footer>
  <script src="{% static 'js/support/accordion.js' %}"></script>
</body>

</html>

viewy/templates/support/inquiry_success.html
{% extends 'support/detail_base.html' %}
{% load static %}
{% block head %}

{% endblock %}

{% block topic %}
<div class="topic-title">お問い合わせ</div>
<div class="sub-topics">
  <div class="sub-topic">
    お問い合わせありがとうございます。
    <p class="paragraph"><br>ご入力いただいたメールアドレスに確認メールを送信しました。<br>お問い合わせの内容によっては、回答に時間がかかる場合や回答できない場合があります。</p>
  </div>
</div>

{% endblock %}